/*

  -! Credits By Kevintech 
  Thanks to  great lonelysaam 
  https://wa.me/256742932677

*/

// setting/config.js
const fs = require('fs')

// ========= Setting Owner ========= //
global.owner = ["256742932677", "256755585369"];
global.ownername = "Kevin tech";
global.botname = "Vinic-Xmd";

// ========= Setting Channel ========= //
global.namasaluran = "KEVIN";
global.idsaluran = "120363398454335106@newsletter";
global.linksaluran = "";
global.SESSION_ID = "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0F6amxJam9VNDNnbnQxcTByWHgyMDlCZm1lNmNmMUloZDdCb3RRMmgybz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0RQVlBlVnA2ZTMwV1JiMVladU5rdGFnRmRuaGxtQ0k0MElDMERKNnFuVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVUGkrc3RyQmxjK25FcDB6RkVZY2JLR25JQmdwK1pGZzVnNzRXK1JMZEhRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsb1lwQkcvdFR4RS8yYUEvelVjUzQwWGp0NjdhUGcrUTMvVmVWdlJjcnk0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFDK3BTbFNhS1pLUEF1NStud0UvVkJ2czdPQkJmRnR0eHhuemxvU2tjVnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikg2ZFF6aUdGYXhWcEVRVGo1MjVuR3dCc2YwaC9xeFVwZFZtRSt5bHJ1eFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUxRMzZHRk95TVBTZFV6R2xrZ1Qwd0ZKREt2QkFObnZmelFaa3AvWlFXdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRk9kRU5qSUdBbEtDTXl1dmwwY2hSbExwTitsLyt6cFp6Q2ZtOUcyODlnOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRrMkM3S09vWml3UU12RVZOUE1yTkxwTXM1TjVObUYvb0hMQzlaaEtSWmFDMlBoR0dtNm10YnAwcFQxMXpaeTJVUWdyQ0pGOE81dlhKUWRlNE1Hb2pRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAwLCJhZHZTZWNyZXRLZXkiOiJyR0ZXUXQ1QmFKd1BVQitGRjFSVFkzL21FZ0FvZy9RSWFJVGpObHNoeFQwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJTQUQ4NkVNMSIsIm1lIjp7ImlkIjoiMjU0NzA4NTYzMDkzOjZAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI3OTE3NDA2NDcyNjIzMzo2QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTnpHMStVRkVLT01nY1lHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoibitNbk54TXRiTGdvTThBcVkyNW12Zlg1UTBjdTFEcllxeDFpSDlqZ095RT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiVUNaODZMb3N2REN2OFFmU2MyNUoraEtNRUkvbERZNHdibUdiYUJRVk1mVVV6b1phZUpQNWp5WWZkb3h3TXBmeWJXdzAzNGNBTTBkeW5qdzk5OVJWQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6IlZCWUFSTE1lUnNSS29OOHBXcXJReEJVVmJUVWxybnVZZTNiTWdESVR1WVdBOEdoMklaQXJMNWZUdlZrbUtnNDAwREQ5K2tzcGJ5UXRKVFZUTmU4dGd3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzA4NTYzMDkzOjZAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWi9qSnpjVExXeTRLRFBBS21OdVpyMzErVU5ITHRRNjJLc2RZaC9ZNERzaCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3NDMxMzQ2LCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU1lMSJ9"; 

// ========= Setting Status ========= //
global.autostatus = true;
global.antispam = true;
global.autoread = false;
// setting/config.js - Add this to your config
global.anticall = "on", "decline", "block" 
global.antilink = true;
global.autoreact = false
global.antibug = true;
global.autobio = false;
global.chatbot = false;
global.autoTyping = false;
global.autorecording = false;
global.prefa = ['', '!', '.', ',', 'ðŸ¤', 'ðŸ¦¦'];

// ========= Anti-Delete Feature ========= //
global.antidelete = true; // Set to false to disable anti-delete feature

// ========= Other Global Settings ========= //
global.welcome = true; // welcome setting
global.adminevent = true; // admin event setting

// ========= Add modeStatus and versions ========= //
global.modeStatus = "Private"; // Added for connection notice
global.versions = "1.2.5"; // Added for connection notice

// ========= Setting WM ========= //
global.packname = 'Vinic';
global.author = 'Xmd';

global.gcount = {
    prem: 500,
    user: 15
};

global.limitCount = 10;

global.mess = {
    group: "*This is not a group*",
    admin: "*To use this feature first make Vinic-Xmd admin*",
    owner: "*Sorry broðŸ˜›, your not my owner*",
    premium: "*First become a premium user*",
    botadmin: "*Vinic-Xmd needs to be admin*",
    limited: "/Limit reached*"
};

let file = require.resolve(__filename)
require('fs').watchFile(file, () => {
  require('fs').unwatchFile(file)
  console.log('\x1b[0;32m'+__filename+' \x1b[1;32mupdated!\x1b[0m')
  delete require.cache[file]
  require(file)
})
